# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Hrkt',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Scklk',
        ),
    ]
