# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160618_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrkt',
            old_name='ver3',
            new_name='verih',
        ),
        migrations.RenameField(
            model_name='scklk',
            old_name='ver1',
            new_name='verin',
        ),
        migrations.RenameField(
            model_name='scklk',
            old_name='ver2',
            new_name='veris',
        ),
    ]
